# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161014_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_signups',
            field=models.IntegerField(help_text='Set to -1 if signup is not required'),
        ),
    ]
