# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
