# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20161017_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-when']},
        ),
    ]
