# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exec',
            options={'verbose_name_plural': 'Exec'},
        ),
        migrations.AlterModelOptions(
            name='historyentry',
            options={'verbose_name_plural': 'History Entries'},
        ),
    ]
