# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0004_auto_20170715_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='exec',
            name='place_in_list',
            field=models.IntegerField(default=100),
        ),
    ]
