# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0005_exec_place_in_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exec',
            options={'ordering': ['-academic_year', 'place_in_list'], 'verbose_name_plural': 'Exec'},
        ),
    ]
