# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0007_auto_20170814_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exec',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
