# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-28 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0009_auto_20180220_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Alerts',
            },
        ),
    ]
