# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-27 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0009_auto_20180220_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
