# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-28 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0010_homealert'),
    ]

    operations = [
        migrations.AddField(
            model_name='homealert',
            name='title',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
