# Generated by Django 2.2.2 on 2020-04-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0011_auto_20190616_1734'),
        ('site_info', '0012_auto_20181012_1819'),
    ]

    operations = [
    ]
