# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
