# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
