# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20161007_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='next_post',
        ),
    ]
