# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_post_next_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(default='desc', max_length=150),
            preserve_default=False,
        ),
    ]
