# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20161009_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='original',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
