# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20170920_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Member'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='parent_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.Board'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Member'),
        ),
    ]
