# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20170924_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
