# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_post_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
