# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_board_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
