# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-26 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_board_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
