# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-27 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0013_board_locked'),
    ]

    operations = [
        # Removed to prevent crashing when migrating
        # migrations.AddField(
        #    model_name='thread',
        #    name='originalPost',
        #    field=models.IntegerField(default=False),
        # ),
        # migrations.AddField(
        #    model_name='thread',
        #    name='pinned',
        #    field=models.BooleanField(default=False),
        # ),
    ]
