# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-27 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_thread_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='originalPost',
            field=models.IntegerField(default=False),
        ),
    ]
