# Generated by Django 2.2.2 on 2019-06-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20180927_2204'),
        ('forum', '0015_thread_originalpost'),
    ]

    operations = [
    ]
