# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-08 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0018_auto_20180220_2058'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='name',
        ),
        migrations.AddField(
            model_name='options',
            name='details',
            field=models.CharField(help_text=b'Episodes watched (Ep.1, Eps. 1-3), etc.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='lib_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='library.Series'),
        ),
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.CharField(help_text=b'Description of the poll', max_length=50, null=True),
        ),
    ]
