# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-11 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_option_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='details',
            field=models.CharField(help_text='Episodes watched (Ep.1, Eps. 1-3), etc.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.CharField(help_text='Description of the poll', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(help_text='Enter name of poll', max_length=30),
        ),
    ]
