# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-26 23:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_option_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='voters',
            field=models.CharField(default=b'', max_length=999, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
