# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-27 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_voters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(default=b'', editable=False, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='voters',
        ),
        migrations.AddField(
            model_name='voter',
            name='memberOf',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
    ]
