# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-15 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180827_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='memberOf',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='polls.Poll'),
        ),
    ]
