# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-27 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180811_1853'),
        ('polls', '0007_auto_20180827_0114'),
    ]

    operations = [
    ]
