# Generated by Django 2.2.2 on 2019-06-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180927_2204'),
        ('polls', '0008_auto_20181215_1420'),
    ]

    operations = [
    ]
