# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text=b'Displayed name rather than file name (Note. filename will still be shown)', max_length=40, null=True)),
                ('type', models.CharField(choices=[(b'im', b'Image'), (b'tx', b'Text File'), (b'we', b'Website File')], default=b'tx', max_length=2)),
                ('date', models.DateField(help_text=b'Date of creation or last known time')),
                ('file', models.FileField(help_text=b'The file that should be uploaded', upload_to=b'')),
                ('details', models.TextField(blank=True, help_text=b'Any details about the item', null=True)),
            ],
        ),
    ]
