# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-15 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(help_text='Date of creation or last known time'),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.TextField(blank=True, help_text='Any details about the item', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(help_text='The file that should be uploaded', upload_to='archive/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, help_text='Displayed name rather than file name (Note. filename will still be shown)', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('im', 'Image'), ('tx', 'Text File'), ('we', 'Website File')], default='tx', max_length=2),
        ),
    ]
