# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-15 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(help_text=b'The file that should be uploaded', upload_to=b'archive/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[(b'im', b'Image'), (b'vi', b'Video'), (b'tx', b'Text File'), (b'we', b'Website File')], default=b'tx', max_length=2),
        ),
    ]
