# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-15 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20181215_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('im', 'Image'), ('vi', 'Video'), ('tx', 'Text File'), ('we', 'Website File')], default='tx', max_length=2),
        ),
    ]
