# Generated by Django 2.2.2 on 2019-06-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20181215_2006'),
        ('archive', '0002_auto_20181215_2009'),
    ]

    operations = [
    ]
