# Generated by Django 2.2.2 on 2019-06-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_merge_20190616_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(help_text='The file that should be uploaded', upload_to='archive/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('im', 'Image'), ('vi', 'Video'), ('tx', 'Text File'), ('we', 'Website File')], default='tx', max_length=2),
        ),
    ]
