# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('api_id', models.CharField(blank=True, max_length=20)),
                ('cover_link', models.URLField(blank=True)),
                ('synopsis', models.TextField(blank=True)),
                ('mal_link', models.URLField(blank=True)),
                ('wiki_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'series',
            },
        ),
    ]
