# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='ani_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='api_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
