# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20160730_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='last_api_update',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover_link',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='synopsis',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
