# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20160730_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='last_api_update',
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(blank=True, max_length=110),
        ),
    ]
