# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20160803_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='media_type',
            field=models.CharField(choices=[('manga', 'API id is for Manga'), ('anime', 'API id is for Anime')], default='manga', max_length=5),
        ),
    ]
