# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_series_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='ani_link',
            field=models.URLField(blank=True, editable=False),
        ),
    ]
