# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_auto_20160803_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='api_id',
            field=models.CharField(max_length=20),
        ),
    ]
