# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0007_auto_20160803_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='ani_link',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover_link',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(editable=False, max_length=110),
        ),
        migrations.AlterField(
            model_name='series',
            name='synopsis',
            field=models.TextField(editable=False),
        ),
    ]
