# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0009_auto_20160805_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(default='memes', editable=False),
            preserve_default=False,
        ),
    ]
