# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0011_remove_series_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='ani_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='series',
            name='synopsis',
            field=models.TextField(),
        ),
    ]
