# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0007_auto_20160921_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110)),
                ('title_eng', models.CharField(max_length=110)),
                ('details', models.CharField(max_length=200)),
                ('api_id', models.IntegerField()),
                ('ani_link', models.URLField()),
                ('mal_link', models.URLField(blank=True)),
                ('wiki_link', models.URLField(blank=True)),
                ('lib_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.Series')),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('showing_type', models.CharField(choices=[('wk', 'Weekly showing'), ('an', 'Allnighter')], default='wk', max_length=2)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='shown_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showings.Showing'),
        ),
    ]
