# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='api_id',
            new_name='anilist_anime_number',
        ),
        migrations.RenameField(
            model_name='showing',
            old_name='details',
            new_name='additional_details',
        ),
        migrations.AlterField(
            model_name='show',
            name='wiki_link',
            field=models.URLField(),
        ),
    ]
