# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0003_remove_showing_additional_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='details',
            field=models.CharField(help_text=b'Episodes watched etc.', max_length=200),
        ),
    ]
