# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0005_auto_20170809_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='cooldown_period',
            field=models.IntegerField(default=0, help_text=b'Will be filled when saving according to type of show. Input the value manually to set override.'),
        ),
        migrations.AddField(
            model_name='show',
            name='show_type',
            field=models.CharField(choices=[(b'ms', b'Main series'), (b'mc', b'Main series candidate'), (b'ex', b'Exec choice'), (b'an', b'Allnighter'), (b'ot', b'Other')], default='ot', max_length=2),
            preserve_default=False,
        ),
    ]
