# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0006_auto_20170809_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='cooldown_period',
            field=models.IntegerField(default=0, help_text=b'In days. Will be filled when saving according to type of show. Input the value manually to override.'),
        ),
    ]
