# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0007_auto_20170810_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='details',
            field=models.CharField(help_text=b'Episodes watched (Ep.1, Eps. 1-3), etc.', max_length=200),
        ),
    ]
