# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0009_auto_20170925_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='details',
            field=models.CharField(blank=True, help_text=b'Brief event explanation, etc.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='showing',
            name='showing_type',
            field=models.CharField(choices=[(b'wk', b'Weekly showing'), (b'an', b'Allnighter'), (b'ev', b'Event'), (b'ot', b'Other')], default=b'wk', max_length=2),
        ),
    ]
