# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0010_auto_20170925_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showing',
            options={'ordering': ['-date']},
        ),
    ]
