# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0011_auto_20170925_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='cooldown_period',
            field=models.IntegerField(blank=True, default=0, help_text='In days. Will be filled when saving according to type of show. Input the value manually to override.', null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='details',
            field=models.CharField(help_text='Episodes watched (Ep.1, Eps. 1-3), etc.', max_length=200),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_type',
            field=models.CharField(choices=[('ms', 'Main series'), ('mc', 'Main series candidate'), ('ex', 'Exec choice'), ('an', 'Allnighter'), ('ot', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='showing',
            name='details',
            field=models.CharField(blank=True, help_text='Brief event explanation, etc.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='showing',
            name='showing_type',
            field=models.CharField(choices=[('wk', 'Weekly showing'), ('an', 'Allnighter'), ('ev', 'Event'), ('ot', 'Other')], default='wk', max_length=2),
        ),
    ]
