# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-28 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0012_auto_20180220_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='showing_type',
            field=models.CharField(choices=[(b'wk', b'Weekly showing'), (b'an', b'Allnighter'), (b'ev', b'Event'), (b'mo', b'Movie Night'), (b'ot', b'Other')], default=b'wk', max_length=2),
        ),
    ]
