# Generated by Django 2.2.2 on 2019-06-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0013_auto_20180928_1347'),
        ('showings', '0013_auto_20180928_1312'),
    ]

    operations = [
    ]
