# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
