# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20161003_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='member',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
    ]
