# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20161010_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
