# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20161018_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='show_full_name',
            field=models.BooleanField(default=True),
        ),
    ]
