# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_show_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=b'user_avatars/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='show_full_name',
            field=models.BooleanField(default=False),
        ),
    ]
