# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20170911_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='img',
        ),
    ]
