# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nick',
            field=models.CharField(blank=True, default=b'AniSoc member', max_length=30),
        ),
    ]
