# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20170911_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='img_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
