# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20170925_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(blank=True, height_field='img_height', null=True, storage=members.models.OverwriteStorage(), upload_to=members.models.user_avatar_path, width_field='img_width'),
        ),
    ]
