# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20180220_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='discordTag',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
